{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zwj.zroute.plugin",
    "module": "ZRoutePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ZRoutePlugin-1.0.0.jar",
          "url": "ZRoutePlugin-1.0.0.jar",
          "size": 20099,
          "sha512": "227d7aee75d355a047b908963cc8e49b02758bfe9fb4dc2c459fb0634cb0fb606c4214d8912f566cfa3c456ae841245dd88e492669e6a95c3c110deb3bed8afd",
          "sha256": "96413d4405d44c4b55423e3538e1ef4966d9eab1a3fe77ef1ac90880aa8eb987",
          "sha1": "286f575ee4bbd94bbb23f6750abaf77a6001c604",
          "md5": "9e26cd4679df68a1a02583dbb2919e52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata-specs",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ZRoutePlugin-1.0.0.jar",
          "url": "ZRoutePlugin-1.0.0.jar",
          "size": 20099,
          "sha512": "227d7aee75d355a047b908963cc8e49b02758bfe9fb4dc2c459fb0634cb0fb606c4214d8912f566cfa3c456ae841245dd88e492669e6a95c3c110deb3bed8afd",
          "sha256": "96413d4405d44c4b55423e3538e1ef4966d9eab1a3fe77ef1ac90880aa8eb987",
          "sha1": "286f575ee4bbd94bbb23f6750abaf77a6001c604",
          "md5": "9e26cd4679df68a1a02583dbb2919e52"
        }
      ]
    }
  ]
}
